# Generated by Django 3.1.7 on 2021-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='identi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
