# Generated by Django 3.1.7 on 2021-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmprj', '0002_auto_20210409_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
